## [作業重點]
使用 Sklearn 中的線性迴歸模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義

## 作業
試著使用 sklearn datasets 的其他資料集 (wine, boston, ...)，來訓練自己的線性迴歸模型。

### HINT: 注意 label 的型態，確定資料集的目標是分類還是回歸，在使用正確的模型訓練！

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model  #以前都是from sklearn.linear_model import LinearRegression等等
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, accuracy_score, mean_squared_error

C:\Users\User\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
wine = datasets.load_wine()
boston = datasets.load_boston()
breast_cancer = datasets.load_breast_cancer()

In [13]:
x_train_wine, x_test_wine, y_train_wine, y_test_wine = train_test_split(wine.data, wine.target, test_size=0.1, random_state=4)
print(x_train_wine)
print(y_train_wine)

[[1.229e+01 2.830e+00 2.220e+00 ... 1.150e+00 3.300e+00 2.900e+02]
 [1.384e+01 4.120e+00 2.380e+00 ... 5.700e-01 1.640e+00 4.800e+02]
 [1.200e+01 1.510e+00 2.420e+00 ... 1.050e+00 2.650e+00 4.500e+02]
 ...
 [1.204e+01 4.300e+00 2.380e+00 ... 7.900e-01 2.570e+00 5.800e+02]
 [1.340e+01 3.910e+00 2.480e+00 ... 7.000e-01 1.560e+00 7.500e+02]
 [1.242e+01 4.430e+00 2.730e+00 ... 9.200e-01 3.120e+00 3.650e+02]]
[1 2 1 2 1 2 0 2 1 1 2 2 0 1 0 1 2 2 0 0 0 2 2 0 0 1 1 0 1 2 0 2 1 1 1 0 0
 1 1 1 2 2 0 2 1 1 1 0 2 1 1 0 1 1 1 0 1 2 0 0 1 1 2 2 2 1 0 0 2 0 0 1 0 1
 0 1 2 2 1 1 1 1 1 0 2 2 1 1 1 0 0 1 0 0 0 1 1 2 2 0 2 1 2 0 2 2 1 0 1 0 0
 1 1 0 1 1 2 2 0 1 0 2 1 2 1 1 1 1 0 2 0 2 1 0 2 0 1 0 2 0 0 2 0 1 0 0 2 0
 0 1 1 1 0 2 0 1 1 1 2 1]


In [18]:
model = linear_model.LogisticRegression()
model.fit(x_train_wine, y_train_wine)
y_pred_wine = model.predict(x_test_wine)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [20]:
acc = accuracy_score(y_test_wine, y_pred_wine)
print("Accuracy: ", acc)

Accuracy:  0.9444444444444444
